version: '2'
services:
  vault:
    image: vault:0.6
    command: vault server -config /vault/config
    cap_add:
      - IPC_LOCK
    volumes:
      - ./config:/vault/config
    networks:
      - vault
      - consul
    environment:
      - "VAULT_ADDR=http://127.0.0.1:8200"
networks:
  vault:
    external: true
  consul:
    external: true
